substitutions:
  # Name the device and it's entities
  device: amg8833
  device_name: amg8833_1

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_lite

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 20min

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "$device_name Fallback Hotspot"
    password: !secret ap_password

logger:

api:

ota:
  password: !secret ota_password
  reboot_timeout: 2min

i2c:

amg88xx:
  ir_camera:
    name: $device_name ir camera
  device_temperature:
    name: $device_name device temperature

